import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          style={{
            maxWidth: "420px",
            margin: "0 auto",
            minHeight: "100vh",
            padding: "16px",
            paddingBottom: "96px", // ✅ 하단 고정바 공간 확보
          }}>
          {children}
          <div
            style={{
              position: "fixed",
              left: "50%",
              transform: "translateX(-50%)",
              bottom: 12,
              width: "calc(420px - 32px)",
              maxWidth: "calc(100vw - 32px)",
              zIndex: 50,
            }}>
            <a
              href="tel:01091273024"
              style={{
                display: "block",
                width: "100%",
                textAlign: "center",
                padding: "14px 16px",
                borderRadius: 14,
                background: "#000",
                color: "#fff",
                textDecoration: "none",
                fontWeight: 900,
                boxShadow: "0 8px 24px rgba(0,0,0,0.18)",
              }}>
              📞 전화로 바로 상담 (010-9127-3024)
            </a>

            <div
              style={{
                marginTop: 8,
                textAlign: "center",
                fontSize: 12,
                color: "#666",
              }}>
              문자 상담은 “요청하기”에서 가능해요
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
